// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PressYourLuck.Models;

namespace PressYourLuck.Migrations
{
    [DbContext(typeof(AuditContext))]
    [Migration("20211107234000_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PressYourLuck.Models.AuditType", b =>
                {
                    b.Property<string>("AuditTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditTypeId");

                    b.ToTable("AuditTypes");

                    b.HasData(
                        new
                        {
                            AuditTypeId = "ci",
                            Name = "Cash In"
                        },
                        new
                        {
                            AuditTypeId = "co",
                            Name = "Cash Out"
                        },
                        new
                        {
                            AuditTypeId = "w",
                            Name = "Win"
                        },
                        new
                        {
                            AuditTypeId = "l",
                            Name = "Lose"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
